# Generated by Django 5.0.3 on 2024-03-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_man_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='man',
        ),
    ]
