# Generated by Django 5.0.3 on 2024-03-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_file_man'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('new_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.newmod')),
            ],
        ),
    ]
