# Generated by Django 5.0.3 on 2024-03-13 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_newmod_uploadm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadm',
            name='new_mod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.newmod'),
        ),
    ]
