# Generated by Django 5.0.3 on 2024-03-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_uploadm_new_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='man',
        ),
        migrations.RemoveField(
            model_name='uploadm',
            name='new_mod',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Man',
        ),
        migrations.DeleteModel(
            name='NewMod',
        ),
        migrations.DeleteModel(
            name='UploadM',
        ),
    ]
