# Generated by Django 5.0.3 on 2024-03-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
