# Generated by Django 5.0.3 on 2024-03-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testone',
            name='one',
        ),
        migrations.AddField(
            model_name='testtwo',
            name='one',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.testone'),
            preserve_default=False,
        ),
    ]
