# Generated by Django 5.0.3 on 2024-03-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_testone_one_testtwo_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtwo',
            name='one',
        ),
        migrations.DeleteModel(
            name='TestOne',
        ),
        migrations.DeleteModel(
            name='TestTwo',
        ),
    ]
