# Generated by Django 5.0.3 on 2024-03-14 14:50

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0011_remove_testtwo_one_delete_testone_delete_testtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('copies', models.IntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(null=True)),
                ('accepted', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(max_length=5)),
                ('file_count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.orderdetails'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('gmap_link', models.URLField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.store'),
        ),
    ]
