# Generated by Django 5.0.3 on 2024-03-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='uid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
