# Generated by Django 5.0.3 on 2024-03-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_store_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reference_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='copies',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
