# Generated by Django 5.0.3 on 2024-03-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_file_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_count',
        ),
    ]
