# Generated by Django 5.0.3 on 2024-05-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_pricing_store_pricing_storeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='per_page',
            new_name='color_2side',
        ),
        migrations.AddField(
            model_name='pricing',
            name='normal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='normal_2side',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
