# Generated by Django 5.0.3 on 2024-05-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_pricing_color_alter_pricing_color_2side_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeimage',
            name='image',
        ),
        migrations.AddField(
            model_name='storeimage',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
