# Generated by Django 5.0.3 on 2024-05-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_storeimage_image_storeimage_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreImage',
        ),
    ]
